sulu_page.page.versions:
    type: rest
    name_prefix: sulu_page.
    parent: sulu_page.page
    resource: sulu_page.version_controller

sulu_page.post_page_version_trigger:
    path: /pages/{id}/versions/{version}.{_format}
    methods: POST
    defaults:
        _controller: sulu_page.version_controller::postTriggerAction
        _format: json
