sulu_website.sitemap_index:
    path:      /sitemap.xml
    defaults:  { _controller: Sulu\Bundle\WebsiteBundle\Controller\SitemapController::indexAction }

sulu_website.paginated_sitemap:
    path:      /sitemaps/{alias}-{page}.xml
    defaults:  { _controller: Sulu\Bundle\WebsiteBundle\Controller\SitemapController::sitemapPaginatedAction }
    requirements: {page: \d+}

sulu_website.sitemap:
    path:      /sitemaps/{alias}.xml
    defaults:  { _controller: Sulu\Bundle\WebsiteBundle\Controller\SitemapController::sitemapAction }
