sulu_website.sitemap_index:
    path:      /sitemap.xml
    defaults:  { _controller: sulu_website.sitemap_controller::indexAction }

sulu_website.paginated_sitemap:
    path:      /sitemaps/{alias}-{page}.xml
    defaults:  { _controller: sulu_website.sitemap_controller::sitemapPaginatedAction }
    requirements: {page: \d+}

sulu_website.sitemap:
    path:      /sitemaps/{alias}.xml
    defaults:  { _controller: sulu_website.sitemap_controller::sitemapAction }
