sulu_custom_urls:
    type: rest
    name_prefix: sulu_custom_url.
    parent: sulu_page.webspace
    resource: sulu_custom_urls.custom_url_controller

sulu_custom_url_routes:
    type: rest
    name_prefix: sulu_custom_url.
    parent: sulu_custom_urls
    resource: sulu_custom_urls.custom_url_route_controller
